---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "grafana-datasource-auth-proxy.fullname" . }}"
  labels:
    app.kubernetes.io/name: "{{ include "grafana-datasource-auth-proxy.name" . }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ include "grafana-datasource-auth-proxy.chart" . }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ include "grafana-datasource-auth-proxy.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: http
      port: 3000
